### ISSUE TITLE
Add server test coverage

### ISSUE THREAD

**Issue by fmunoz92** [QActivo/mean#40]
Now just include client test coverage.

**Comment by rowlandekemezie** [comment]
@fmunoz92 since there's no gulp task to run the test, would you prefer to define a gulp task for it and then a server side test coverage task or merge the two?

**Comment by fmunoz92** [comment]
Hey @andela-rekemezie ! yes! there are two gulp tasks

``` bash
gulp test # client side
gulp server-tests # server side
```

check npm coverage script in package.json, maybe We can use something like that in gulp

**Comment by rowlandekemezie** [comment]
@fmunoz92 the ideal thing is to move them to gulpfile and then specify tasks for each. I'll check it out and see if I can help.

**Comment by fmunoz92** [comment]
@andela-rekemezie perfect! thanks :)
