### ISSUE TITLE
Fix 404 page

### ISSUE THREAD

**Issue by fmunoz92** [QActivo/mean#44]
404 page styles are broken 

http://localhost:3000/asdasd
->
http://localhost:3000/404

**Comment by jayMcoder** [comment]
@fmunoz92 Can I work on this issue?

**Comment by fmunoz92** [comment]
@JayOnCaffeine sure! thanks!

**Comment by jayMcoder** [comment]
@fmunoz92 Issue is because of missing "ht-widget-header" directive and widget related CSS entries. Do you have image of previous working page or any specific design in mind how the page should look?

**Comment by fmunoz92** [comment]
@JayOnCaffeine thanks. Yes, there are previous work, We used https://github.com/johnpapa/generator-hottowel for the client side.
