### ISSUE TITLE
Create one Gulp Task to run client & server tests

### ISSUE THREAD

**Issue by fmunoz92** [QActivo/mean#50]
Join both tests in just one gulp task to update coveralls and travis-ci.
- Update gulpfile.babel.js
- Update package.json commands
- Update Readme.md
- Check [travis-ci](https://travis-ci.org/QActivo/express-angular-starter)
- Check [coveralls](https://coveralls.io/github/QActivo/express-angular-starter)

**Comment by fmunoz92** [comment]
@andela-rekemezie The client side errors was fixed, can you update your collaborations to run client side tests too? Thanks.

**Comment by rowlandekemezie** [comment]
@fmunoz92 What do you think about having two coverage badges for the repo? The client and server side test can only be separate. So, we can use coveralls for backend and maybe codecov for front end report. OR we can use only Travis to report build status. The danger using the later is that you would not know when the coverage is dropping.

**Comment by fmunoz92** [comment]
@andela-rekemezie okay, sounds good!

**Comment by fmunoz92** [comment]
@andela-rekemezie can you see how [meanjs](https://github.com/meanjs/mean) have both tests in just one command?

**Comment by rowlandekemezie** [comment]
@fmunoz92 Do you intend fixing the CI error from your end?

**Comment by fmunoz92** [comment]
@andela-rekemezie yes! I just fixed. We need to improve our coverage now! Please feel free to new PR or open new issues
Thank you very much!

**Comment by rowlandekemezie** [comment]
@fmunoz92 no qualms. I have some tech assessments and maybe when I'm done in the coming weeks, I can see how to contribute more to the project. Love the initiative and responsiveness.
