### ISSUE TITLE
Improve documentation. README.md

### ISSUE THREAD

**Issue by fmunoz92** [QActivo/mean#54]
Improve documentation. README.md

**Comment by vikashvverma** [comment]
Hey @fmunoz92 I would like to help. Can you elaborate what kind of improvement you need?

**Comment by fmunoz92** [comment]
@vikashvverma cool! thanks. Sure, I want an explanation of the architecture, improve how to run in development mode, in production, how to deploy in heroku. like [MEANJS](https://github.com/meanjs/mean/blob/master/README.md).

**Comment by fmunoz92** [comment]
thanks @fgriberi
